type Post {
    id: ID!
    title: String!
    subtitle: String
    content: String!
    image: String
    createdAt: Date!
    updatedAt: Date!
    author: AuthorPayload
    authorId: ID!
    comments: [CommentPayload]
    likes: [FavoritePostByUser]
    popularity: Float
}

type ResentPost {
    id: ID!
    title: String!
    subtitle: String
    content: String!
    image: String
    createdAt: Date!
    updatedAt: Date!
    authorId: ID!
}


type PostList {
    posts: [Post]
    total: String
}

input UpdatePostInput {
    id: ID!
    title: String
    content: String
    subtitle: String
}

input CreatePostInput {
    id: ID!
    title: String!
    content: String!
    subtitle: String
}

type Query {
    getPosts(page: String sortOrder: String): PostList
    getSearchPosts(search: String!): PostList
    getPost(id: ID!): Post
    getResentPosts(id: ID!): [ResentPost]
}

type Mutation {
    updatePost(input: UpdatePostInput!, image: File): Post!
    deletePost(id:ID!): Post!
    createPost(input: CreatePostInput!, image: File): Post!
}
